using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
/*
 * Author: N. Abdurakhmonova, 
 * Assistant: D.Mengliev
 * Year: 2020
 * Description: This class contains types of exceptions, which might be generated by system
 * when it works. This is technical exception, not a word exception.
 * Описание: Этот класс содержит типы исключений, которые могут быть сгенерированы системой
 * когда она работает. Это техническое исключение, а не словесное исключение (например: ExceptionNouns).
 */

namespace GenerationN.Exceptions
{
    [Serializable]
    public class InvalidTextException : ApplicationException
    {
        public InvalidTextException() { }
        public InvalidTextException(string message) : base(message) { }
        public InvalidTextException(string message, System.Exception inner)
            :base(message, inner) { }
        public InvalidTextException(System.Runtime.Serialization.SerializationInfo info,
            System.Runtime.Serialization.StreamingContext context) : base(info, context) { }
    }
}
