using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Morphoanalyzer.Exceptions
{
    public class VerbRootBase
    {

        public Dictionary<string, string> Dict;
        public static string personsEndings = "Root word is verb";
        public static string personsEndingsRus = "Окончание, формирующее  существительное - личность";
        public static string objectEndings = "Ending, which forms the noun (object or subject)";
        public static string objectEndingsRus = "Окончание, формирующее существительное - предмет или объект";

        public VerbRootBase()
        {
            Dict = new Dictionary<string, string>(Verb);
        }

        private readonly Dictionary<string, string> Verb = new Dictionary<string, string>()
        {
            { "abadiylash", "root word - verb"},
            { "abadiylashtirish", " Root word (verb) is made from noun" },
            { "abstraktlashtir", " Root word is verb" },
            { "abadiylashtiril", "Root word is verb" },
            { "abadiylashtiruv", " Root word (verb) is made from noun" },
            { "abadiylashuv", " Root word (verb) is made from noun" },
            { "abgorlan", " root word - verb" },
            { "abgorlanish", " Root word (verb) is made from noun" },
            { "abgorlanuv", " Root word (verb) is made from noun" },
            { "abjaq", " root word - verb" },
            { "abjaqla", " root word - verb" },
            { "abjaqlan", " root word - verb" },
            { "abjaqlanuv", " Root word (verb) is made from noun" },
            { "abjirlan", " root word - verb" },
            { "abjirlanish", " Root word (verb) is made from noun" },
            { "abjirlash", " Root word (verb) is made from noun" },
            { "ablahlash", " root word - verb" },
            { "absorbla", " root word - verb" },
            { "absorblanish", " Root word (verb) is made from noun" },
            { "absorblash", " Root word (verb) is made from noun" },
            { "abstraksiyalash", " Root word (verb) is made from noun" },
            { "abstraktla", " root word - verb" },
            { "abstraktlan", " root word - verb" },
            { "abstraktlash", " Root word (verb) is made from noun" },
            { "abstraktlashish", " Root word (verb) is made from noun" },
            { "abstraktlashtiril", "Root word is verb" },
            { "abstraktlashtirish", " Root word (verb) is made from noun" },
            { "abstraktlashtiruv", " Root word (verb) is made from noun" },
            { "abxazchala", " root word - verb" },
            { "abxazchalashtirish", " Root word (verb) is made from noun" },
            { "abzalla", " root word - verb" },
            { "abzallan", " root word - verb" },
            { "abzallov", " Root word (verb) is made from noun" },
            { "achchig'lan", " root word - verb" },
            { "achchiqla", " root word - verb" },
            { "achchiqlan", " root word - verb" },
            { "achchiqlanish", " Root word (verb) is made from noun" },
            { "achchiqlantir", " Root word is verb" },
            { "achchiqlantirish", " Root word (verb) is made from noun" },
            { "achchiqlanuv", " Root word (verb) is made from noun" },
            { "achchiqlash", " root word - verb" },
            { "achchiqlashuv", " Root word (verb) is made from noun" },
            { "achi", " root word - verb" },
            { "achin", " root word - verb" },
            { "achinish", " Root word (verb) is made from noun" },
            { "achinmas", "Root word is verb" },
            { "achinqira", " root word - verb" },
            { "achinqirash", " Root word (verb) is made from noun" },
            { "achintir", " Root word is verb" },
            { "achintirish", " Root word (verb) is made from noun" },
            { "achintiruv", " Root word (verb) is made from noun" },
            { "achinuv", " Root word (verb) is made from noun" },
            { "achish", " root word - verb" },
            { "achishish", " Root word (verb) is made from noun" },
            { "achishtir", " Root word is verb" },
            { "achishtirish", " Root word (verb) is made from noun" },
            { "achishtiruv", " Root word (verb) is made from noun" },
            { "achishuv", " Root word (verb) is made from noun" },
            { "achit", " root word - verb" },
            { "achitish", " Root word (verb) is made from noun" },
            { "achittir", " Root word is verb" },
            { "achittirish", " Root word (verb) is made from noun" },
            { "achittiruv", " Root word (verb) is made from noun" },
            { "achituv", " Root word (verb) is made from noun" },
            { "achomla", " root word - verb" },
            { "achomlash", " Root word (verb) is made from noun" },
            { "achomlashish", " Root word (verb) is made from noun" },
            { "achomlov", " Root word (verb) is made from noun" },
            { "adabiylashtir", " Root word is verb" },
            { "adabiylashtirish", " Root word (verb) is made from noun" },
            { "adabsizlan", " root word - verb" },
            { "adaptatsiyala", " root word - verb" },
            { "adaptatsiyalangan", "Root word is verb" },
            { "adash", " root word - verb" },
            { "adashgan", "Root word is verb" },
            { "adashish", " Root word (verb) is made from noun" },
            { "adashtir", " root word - verb" },
            { "adashtiril", "Root word is verb" },
            { "adashtirish", " Root word (verb) is made from noun" },
            { "adashtiruv", " Root word (verb) is made from noun" },
            { "adashuv", " Root word (verb) is made from noun" },
            { "adipla", " root word - verb" },
            { "adiplash", " Root word (verb) is made from noun" },
            { "adiplatish", " Root word (verb) is made from noun" },
            { "adiplov", " Root word (verb) is made from noun" },
            { "ado bo‘l", " root word - verb" },
            { "ado et", " root word - verb" },
            { "ado qil", " root word - verb" },
            { "adoqla", " root word - verb" },
            { "adoyi", " root word - verb" },
            { "adreslan", " root word - verb" },
            { "adsorbla", " root word - verb" },
            { "adsorblangan", "Root word is verb" },
             { "adsorblash", " Root word (verb) is made from noun" },
            { "aerochanglash", " Root word (verb) is made from noun" },
            { "aeroionlash", " Root word (verb) is made from noun" },
            { "afg'onchalash", " root word - verb" },
            { "afgorlan", " root word - verb" },
            { "afshonla", " root word - verb" },
            { "afshonlan", " root word - verb" },
            { "afsonaviylash", " Root word (verb) is made from noun" },
            { "afsunla", " root word - verb" },
            { "afsus qil", " root word - verb" },
            { "afsuslan", " root word - verb" },
            { "afsuslanish", " Root word (verb) is made from noun" },
            { "afsuslanuv", " Root word (verb) is made from noun" },
            { "afv et", " root word - verb" },
            { "ag‘dar", " root word - verb" },
            { "ag‘na", " root word - verb" },
            { "ag‘ray", " root word - verb" },
            { "ag'darish", " Root word (verb) is made from noun" },
            { "ag'dart", " root word - verb" },
            { "ag'dartir", " Root word is verb" },
            { "ag'dartirish", " Root word (verb) is made from noun" },
            { "ag'daruv", " Root word (verb) is made from noun" },
            { "aglomeratlash", " Root word (verb) is made from noun" },
            { "ag'nash", " Root word (verb) is made from noun" },
            { "ag'nat", " Root word is verb" },
            { "agregatlash", " Root word (verb) is made from noun" },
            { "ahamiyat ber", " root word - verb" },
            { "ahd qil", " root word - verb" },
            { "ahdlash", " root word - verb" },
            { "ahdlashish", " Root word (verb) is made from noun" },
            { "ahdlashuv", " Root word (verb) is made from noun" },
            { "ahillash", " root word - verb" },
            { "ahillashish", " Root word (verb) is made from noun" },
            { "ahillashuv", " Root word (verb) is made from noun" },
            { "ahmoq qil", " root word - verb" },
            { "ahvollash", " Root word (verb) is made from noun" },
            { "ajablan", " root word - verb" },
            { "ajablanish", " Root word (verb) is made from noun" },
            { "ajablantir", " Root word is verb" },
            { "ajablantirish", " Root word (verb) is made from noun" },
            { "ajablanuv", " Root word (verb) is made from noun" },
            { "ajabsin", " root word - verb" },
            { "ajabsinish", " Root word (verb) is made from noun" },
            { "ajabsinqira", " root word - verb" },
            { "ajabsinuv", " Root word (verb) is made from noun" },
            { "ajilla", " root word - verb" },
            { "ajillash", " Root word (verb) is made from noun" },
            { "ajillashish", " Root word (verb) is made from noun" },
            { "ajillashuv", " Root word (verb) is made from noun" },
            { "ajillov", " Root word (verb) is made from noun" },
            { "ajra", " root word - verb" },
            { "ajragan", "Root word is verb" },
            { "ajral", " root word - verb" },
            { "ajralish", " Root word (verb) is made from noun" },
            { "ajralishuv", " Root word (verb) is made from noun" },
            { "ajraluv", " Root word (verb) is made from noun" },
            { "ajrash", " root word - verb" },
            { "ajrashish", " Root word (verb) is made from noun" },
            { "ajrat", " root word - verb" },
            { "ajratil", "Root word is verb" },
            { "ajratilish", " Root word (verb) is made from noun" },
            { "ajratish", " Root word (verb) is made from noun" },
            { "ajrattir", " Root word is verb" },
            { "ajrattirish", " Root word (verb) is made from noun" },
            { "ajrattiruv", " Root word (verb) is made from noun" },
            { "ajratuv", " Root word (verb) is made from noun" },
            { "ajrimla", " root word - verb" },
            { "ajrimlan", " root word - verb" },
            { "ajrimlash", " Root word (verb) is made from noun" },
            { "ajrimlov", " Root word (verb) is made from noun" },
            { "akakla", " root word - verb" },
            { "akaklat", " Root word is verb" },
            { "akaklov", " Root word (verb) is made from noun" },
            { "akashaklan", " root word - verb" },
            { "akilla", " root word - verb" },
            { "akillash", " Root word (verb) is made from noun" },
            { "akillat", " Root word is verb" },
            { "akillatish", " Root word (verb) is made from noun" },
            { "akillov", " Root word (verb) is made from noun" },
            { "akkreditlash", " Root word (verb) is made from noun" },
            { "akkumulyatsiyalash", " Root word (verb) is made from noun" },
            { "akllash", " root word - verb" },
            { "aks et", " root word - verb" },
            { "akseptla", " root word - verb" },
            { "akseptlash", " Root word (verb) is made from noun" },
            { "aksir", " root word - verb" },
            { "aksirish", " Root word (verb) is made from noun" },
            { "aksirtir", " Root word is verb" },
            { "aksirtirish", " Root word (verb) is made from noun" },
            { "aksiruv", " Root word (verb) is made from noun" },
            { "aksiyalashtir", " Root word is verb" },
            { "aksiyalashtirish", " Root word (verb) is made from noun" },
            { "akslan", " root word - verb" },
            { "akslanish", " Root word (verb) is made from noun" },
            { "akslantir", " root word - verb" },
            { "akslantirish", " Root word (verb) is made from noun" },
            { "akslanuv", " Root word (verb) is made from noun" },
            { "aktivla", " root word - verb" },
            { "aktivlangan", "Root woord is verb" },
            { "aktivlanish", " Root word (verb) is made from noun" },
            { "aktivlantiril", "Root word is verb" },
            { "aktivlantirish", " Root word (verb) is made from noun" },
            { "aktivlash", " root word - verb" },
            { "aktivlashish", " Root word (verb) is made from noun" },
            { "aktivlashtir", " Root word is verb" },
            { "aktivlashtirish", " Root word (verb) is made from noun" },
            { "aktivlashuv", " Root word (verb) is made from noun" },
            { "alag'dalan", "Root word is verb" },
            { "alag'dalanish", " Root word (verb) is made from noun" },
            { "alahla", " root word - verb" },
            { "alahlash", " Root word (verb) is made from noun" },
            { "alahsira", " root word - verb" },
            { "alahsirash", " Root word (verb) is made from noun" },
            { "alamlan", " root word - verb" },
            { "alangala", " root word - verb" },
            { "alangalan", " root word - verb" },
            { "alangalanish", " Root word (verb) is made from noun" },
            { "alangalantir", " Root word is verb" },
            { "alangalantirish", " Root word (verb) is made from noun" },
            { "alangalanuv", " Root word (verb) is made from noun" },
            { "alangalat", "Root word is verb" },
            { "alangalatish", " Root word (verb) is made from noun" },
            { "alang-jalangla", " root word - verb" },
            { "alang-jalanglash", " Root word (verb) is made from noun" },
            { "alangla", " root word - verb" },
            { "alanglash", " Root word (verb) is made from noun" },
            { "alanglov", " Root word (verb) is made from noun" },
            { "alasla", " root word - verb" },
            { "alaslov", " Root word (verb) is made from noun" },
            { "alaxsi", " root word - verb" },
            { "alaxsirash", " Root word (verb) is made from noun" },
            { "alaxsish", " Root word (verb) is made from noun" },
            { "alaxsit", "Root word is verb" },
            { "alaxsitish", " Root word (verb) is made from noun" },
            { "albanchalash", " Root word (verb) is made from noun" },
            { "albitit", " Root word is verb" },
            { "albitlanish", " Root word (verb) is made from noun" },
            { "alda", " root word - verb" },
            { "aldan", " root word - verb" },
            { "aldanil", "Root word is verb" },
            { "aldanish", " Root word (verb) is made from noun" },
            { "aldanma", " root word - verb" },
            { "aldanuv", " Root word (verb) is made from noun" },
            { "aldash", " Root word (verb) is made from noun" },
            { "aldashish", " Root word (verb) is made from noun" },
            { "aldashuv", " Root word (verb) is made from noun" },
            { "aldat", "Root woord is verb" },
            { "aldatish", " Root word (verb) is made from noun" },
            { "alfa-aylanish", " Root word (verb) is made from noun" },
            { "alfa-parchalanish", " Root word (verb) is made from noun" },
            { "alifla", " root word - verb" },
            { "aliflan", " root word - verb" },
            { "aliflash", " Root word (verb) is made from noun" },
            { "aliflov", " Root word (verb) is made from noun" },
            { "alishin", " root word - verb" },
            { "alji", " root word - verb" },
            { "aljira", " root word - verb" },
            { "alkillash", " Root word (verb) is made from noun" },
            { "alla bo‘l", " root word - verb" },
            { "allala", " root word - verb" },
            { "allalash", " Root word (verb) is made from noun" },
            { "allalov", " Root word (verb) is made from noun" },
            { "almash", " root word - verb" },
            { "almashin", " root word - verb" },
            { "almashinuv", " Root word (verb) is made from noun" },
            { "almashish", " Root word (verb) is made from noun" },
            { "almashla", " root word - verb" },
            { "almashtir", " root word - verb" },
            { "almashtirgiz", " Root word is verb" },
            { "almashtiril", "Root word is verb" },
            { "almashtirish", " Root word (verb) is made from noun" },
            { "almashtiruv", " Root word (verb) is made from noun" },
            { "alohidalan", " root word - verb" },
            { "aloqa qil", " root word - verb" },
            { "aloqalantir", " Root word is verb" },
            { "aloqalantiruv", " Root word (verb) is made from noun" },
            { "alpang-talpangla", " root word - verb" },
            { "alpang-talpanglash", " Root word (verb) is made from noun" },
            { "alqa", " root word - verb" },
            { "alqash", " Root word (verb) is made from noun" },
            { "alqish", " Root word (verb) is made from noun" },
            { "alunitlashish", " Root word (verb) is made from noun" },
            { "alushtit", " Root word is verb" },
            { "alyuminiylash", " Root word (verb) is made from noun" },
            { "amal qil", " root word - verb" },
            { "amalgamalangan", "Root word is verb" },
            { "amalgamalash", " Root word (verb) is made from noun" },
            { "amaliylashtir", " Root word is verb" },
            { "amalla", " root word - verb" },
            { "amallan", " root word - verb" },
            { "amallash", " Root word (verb) is made from noun" },
            { "amfibollash", " Root word (verb) is made from noun" },
            { "amidlanish", " Root word (verb) is made from noun" },
            { "aminlash", " Root word (verb) is made from noun" },
            { "ammoniylangan", "Root word is verb" },
            { "ammoniylash", " Root word (verb) is made from noun" },
            { "ammoniylashuv", " Root word (verb) is made from noun" },
            { "amortizatsiyalash", " Root word (verb) is made from noun" },
            { "amr qil", " root word - verb" },
            { "an'anaviylashgan", "Root word is verb" },
            { "andavala", " root word - verb" },
            { "andavalash", " Root word (verb) is made from noun" },
            { "andavalat", " Root word is verb" },
            { "andavalatish", " Root word (verb) is made from noun" },
            { "andavalov", " Root word (verb) is made from noun" },
            { "andaza ol", " root word - verb" },
            { "andazala", " root word - verb" },
            { "andazalash", " Root word (verb) is made from noun" },
            { "andazalov", " Root word (verb) is made from noun" },
            { "andizla", " root word - verb" },
            { "andormon bo‘l", " root word - verb" },
            { "ang‘ishla", " root word - verb" },
            { "angangla", " root word - verb" },
            { "anganglat", " Root word is verb" },
            { "anganglatish", " Root word (verb) is made from noun" },
            { "angilla", " root word - verb" },
            { "angillash", " Root word (verb) is made from noun" },
            { "angillat", " Root word is verb" },
            { "angillatish", " Root word (verb) is made from noun" },
            { "angillatuv", " Root word (verb) is made from noun" },
            { "angillov", " Root word (verb) is made from noun" },
            { "ang'ishlat", " Root word is verb" },
            { "angla", " root word - verb" },
            { "anglan", " root word - verb" },
            { "anglash", " Root word (verb) is made from noun" },
            { "anglashil", " root word - verb" },
            { "anglashuv", " Root word (verb) is made from noun" },
            { "anglat", " Root word is verb" },
            { "anglatil", "Root word is verb" },
            { "anglatish", " Root word (verb) is made from noun" },
            { "anglatuv", " Root word (verb) is made from noun" },
            { "anglezit", " Root word is verb" },
            { "anglov", " Root word (verb) is made from noun" },
            { "angray", " root word - verb" },
            { "ang'raygan", "Root word is verb" },
            { "angYayish", " Root word (verb) is made from noun" },
            { "angYayt", " Root word is verb" },
            { "angYovlan", " root word - verb" },
            { "angYovlanish", " Root word (verb) is made from noun" },
            { "aniqla", " root word - verb" },
            { "aniqlan", " Root word (verb) is made from noun" },
            { "aniqlanish", " Root word (verb) is made from noun" },
            { "aniqlanmish", " Root word (verb) is made from noun" },
            { "aniqlash", " Root word (verb) is made from noun" },
            { "aniqlashtir", " Root word is verb" },
            { "aniqlashtiril", "Root word is verb" },
            { "aniqlashtirish", " Root word (verb) is made from noun" },
            { "aniqlashtiruv", " Root word (verb) is made from noun" },
            { "aniqlat", " Root word is verb" },
            { "aniqlatish", " Root word (verb) is made from noun" },
            { "aniqlov", " Root word (verb) is made from noun" },
            { "anketalash", " Root word (verb) is made from noun" },
            { "annotatsiyalash", " Root word (verb) is made from noun" },
            { "anodlash", " Root word (verb) is made from noun" },
            { "anoyilash", " Root word (verb) is made from noun" },
            { "anoyilashish", " Root word (verb) is made from noun" },
            { "anoyilashuv", " Root word (verb) is made from noun" },
            { "anqay", " root word - verb" },
            { "anqaygan", "Root woord is verb" },
            { "anqayish", " Root word (verb) is made from noun" },
            { "anqaytir", " Root word is verb" },
            { "anqaytirish", " Root word (verb) is made from noun" },
            { "anqayuv", " Root word (verb) is made from noun" },
            { "anqi", " root word - verb" },
            { "anqish", " Root word (verb) is made from noun" },
            { "anqit", " Root word is verb" },
            { "anqitish", " Root word (verb) is made from noun" },
            { "anqovlan", " root word - verb" },
            { "anqovlanish", " Root word (verb) is made from noun" },
            { "anqovsira", " root word - verb" },
            { "anqovsirash", " Root word (verb) is made from noun" },
            { "anqovsirov", " Root word (verb) is made from noun" },
            { "antiaylanish", " Root word (verb) is made from noun" },
            { "antimoslanuv", " Root word (verb) is made from noun" },
            { "antisimmetriyalash", " Root word (verb) is made from noun" },
            { "antratsitlash", " Root word (verb) is made from noun" },
            { "antroponim-apellyativ", " Root word (verb) is made from noun" },
            { "antroponimlashuv", " Root word (verb) is made from noun" },
            { "apash", " Root word (verb) is made from noun" },
            { "apellyativ", " Root word (verb) is made from noun" },
            { "apellyativlashish", " Root word (verb) is made from noun" },
            { "apoq-chapoqlash", " Root word (verb) is made from noun" },
            { "appretlash", " Root word (verb) is made from noun" },
            { "aprobatsiyala", " root word - verb" },
            { "aprobatsiyalash", " Root word (verb) is made from noun" },
            { "apshur", " root word - verb" },
            { "apshurish", " Root word (verb) is made from noun" },
            { "aqir", " root word - verb" },
            { "aqllash", " root word - verb" },
            { "aqllashish", " Root word (verb) is made from noun" },
            { "aqllashuv", " Root word (verb) is made from noun" },
            { "arabchala", " root word - verb" },
            { "arabchalash", " Root word (verb) is made from noun" },
            { "arabchalashtir", " Root word is verb" },
            { "arabchalashtirish", " Root word (verb) is made from noun" },
            { "arabiylashtir", " Root word is verb" },
            { "arabiylashtirish", " Root word (verb) is made from noun" },
            { "aralash", " root word - verb" },
            { "aralashaver", " root word - verb" },
            { "aralashish", " Root word (verb) is made from noun" },
            { "aralashtir", " Root word is verb" },
            { "aralashtiril", "Root word is verb" },
            { "aralashtirish", " Root word (verb) is made from noun" },
            { "aralashtiruv", " Root word (verb) is made from noun" },
            { "aralashuv", " Root word (verb) is made from noun" },
            { "arat", " Root word is verb" },
            { "arazla", " root word - verb" },
            { "arazlash", " Root word (verb) is made from noun" },
            { "arazlashish", " Root word (verb) is made from noun" },
            { "arazlov", " Root word (verb) is made from noun" },
            { "archi", " root word - verb" },
            { "archil", "Root word is verb" },
            { "archilish", " Root word (verb) is made from noun" },
            { "archish", " Root word (verb) is made from noun" },
            { "archishish", " Root word (verb) is made from noun" },
            { "archit", " Root word is verb" },
            { "architish", " Root word (verb) is made from noun" },
            { "archtir", " Root word is verb" },
            { "ardoqla", " root word - verb" },
            { "ardoqlan", " root word - verb" },
            { "ardoqlanish", " Root word (verb) is made from noun" },
            { "ardoqlash", " Root word (verb) is made from noun" },
            { "ardoqlashish", " Root word (verb) is made from noun" },
            { "argumentla", " root word - verb" },
            { "argumentlash", " Root word (verb) is made from noun" },
            { "ari", " root word - verb" },
            { "arid", " Root word is verb" },
            { "arilla", " root word - verb" },
            { "arillash", " Root word (verb) is made from noun" },
            { "arillashuv", " Root word (verb) is made from noun" },
            { "arillat", " Root word is verb" },
            { "arish", " root word - verb" },
            { "arit", " Root word is verb" },
            { "aritil", "Root word is verb" },
            { "aritish", " Root word (verb) is made from noun" },
            { "arittir", " Root word is verb" },
            { "arituv", " Root word (verb) is made from noun" },
            { "armanchala", " root word - verb" },
            { "armanchalash", " Root word (verb) is made from noun" },
            { "armaturalangan", "Root word is verb" },
            { "armon qil", " root word - verb" },
            { "aromatlash", " Root word (verb) is made from noun" },
            { "arqira", " root word - verb" },
            { "arqon sol", " root word - verb" },
            { "arqonla", " root word - verb" },
            { "arqonlan", " root word - verb" },
            { "arqonlash", " Root word (verb) is made from noun" },
            { "arqonlat", " Root word is verb" },
            { "arqonlatish", " Root word (verb) is made from noun" },
            { "arqonlatuv", " Root word (verb) is made from noun" },
            { "arqonlov", " Root word (verb) is made from noun" },
            { "arqov", " Root word (verb) is made from noun" },
            { "arra qil", " root word - verb" },
            { "arrala", " root word - verb" },
            { "arralan", " root word - verb" },
            { "arralanish", " Root word (verb) is made from noun" },
            { "arralash", " Root word (verb) is made from noun" },
            { "arralashuv", " Root word (verb) is made from noun" },
            { "arralat", " Root word is verb" },
            { "arralatish", " Root word (verb) is made from noun" },
            { "arsh qil", " root word - verb" },
            { "arshinla", " root word - verb" },
            { "arshinlash", " Root word (verb) is made from noun" },
            { "art", " root word - verb" },
            { "artil", "Root word is verb" },
            { "artilish", " Root word (verb) is made from noun" },
            { "artin", " root word - verb" },
            { "artinish", " Root word (verb) is made from noun" },
            { "artinuv", " Root word (verb) is made from noun" },
            { "artishish", " Root word (verb) is made from noun" },
            { "artishuv", " Root word (verb) is made from noun" },
            { "artmasdan", " root word - verb" },
            { "arttir", " Root word is verb" },
            { "arttirgiz", " Root word is verb" },
            { "arttirish", " Root word (verb) is made from noun" },
            { "arttiruv", " Root word (verb) is made from noun" },
            { "arvohurgan", "Root word is verb" },
            { "arz qil", " root word - verb" },
            { "arzandalash", " Root word (verb) is made from noun" },
            { "arzi", " root word - verb" },
            { "arzimaydigan", "Root word is verb" },
            { "arzonla", " root word - verb" },
            { "arzonlash", " root word - verb" },
            { "arzonlashish", " Root word (verb) is made from noun" },
            { "arzonlashtir", " Root word is verb" },
            { "arzonlashtirish", " Root word (verb) is made from noun" },
            { "arzonlashuv", " Root word (verb) is made from noun" },
            { "arzonlat", " Root word is verb" },
            { "arzonlatish", " Root word (verb) is made from noun" },
            { "arzonsin", " root word - verb" },
            { "arzonsinish", " Root word (verb) is made from noun" },
            { "arzonsira", " root word - verb" },
            { "asabiyat", " Root word is verb" },
            { "asabiylan", " root word - verb" },
            { "asabiylanish", " Root word (verb) is made from noun" },
            { "asabiylash", " root word - verb" },
            { "asabiylashish", " Root word (verb) is made from noun" },
            { "asabiylashtir", " Root word is verb" },
            { "asabiylashuv", " Root word (verb) is made from noun" },
            { "asbestla", " root word - verb" },
            { "asbestlov", " Root word (verb) is made from noun" },
            { "asfaltit", " Root word is verb" },
            { "asfaltla", " root word - verb" },
            { "asfaltlan", " root word - verb" },
            { "asfaltlanish", " Root word (verb) is made from noun" },
            { "asfaltlash", " Root word (verb) is made from noun" },
            { "asfaltlashtir", " Root word is verb" },
            { "asfaltlashtirish", " Root word (verb) is made from noun" },
            { "asfaltlattir", " Root word (verb) is made from noun" },
            { "asfaltlov", " Root word (verb) is made from noun" },
            { "asokash", " Root word (verb) is made from noun" },
            { "asosla", " root word - verb" },
            { "asoslan", " root word - verb" },
            { "asoslanish", " Root word (verb) is made from noun" },
            { "asoslantir", " Root word is verb" },
            { "asoslantirish", " Root word (verb) is made from noun" },
            { "asoslantiruv", " Root word (verb) is made from noun" },
            { "asoslanuv", " Root word (verb) is made from noun" },
            { "asoslash", " Root word (verb) is made from noun" },
            { "asoslashtir", " Root word is verb" },
            { "asoslashtirish", " Root word (verb) is made from noun" },
            { "asoslilik", " Root word (verb) is made from noun" },
            { "asoslov", " Root word (verb) is made from noun" },
            { "asoslovchi", " Root word (verb) is made from noun" },
            { "asovlash", " Root word (verb) is made from noun" },
            { "asovlashish", " Root word (verb) is made from noun" },
            { "aspiratsiyalash", " Root word (verb) is made from noun" },
            { "asqat", " root word - verb" },
            { "asqatish", " Root word (verb) is made from noun" },
            { "asqatuv", " Root word (verb) is made from noun" },
            { "asra", " root word - verb" },
            { "asral", "Root word is verb" },
            { "asralish", " Root word (verb) is made from noun" },
            { "asran", " root word - verb" },
            { "asrash", " Root word (verb) is made from noun" },
            { "asratish", " Root word (verb) is made from noun" },
            { "asrattir", " Root word is verb" },
            { "asrov", " Root word (verb) is made from noun" },
            { "astabosar", " root word - verb" },
            { "astaiiatish", " Root word (verb) is made from noun" },
            { "astalash", " Root word (verb) is made from noun" },
            { "astalashish", " Root word (verb) is made from noun" },
            { "astalashtirish", " Root word (verb) is made from noun" },
            { "astao'tar", "Root word is verb" },
            { "astarla", " root word - verb" },
            { "astarlash", " Root word (verb) is made from noun" },
            { "astarlat", " Root word is verb" },
            { "astarlov", " Root word (verb) is made from noun" },
            { "astar-paxta", " root word - verb" },
            { "astasuzar", " root word - verb" },
            { "astat", " Root word is verb" },
            { "astayurar", "Root word is verb" },
            { "astoydillanish", " Root word (verb) is made from noun" },
            { "astronavtika", " root word - verb" },
            { "ata", " root word - verb" },
            { "atal", " root word - verb" },
            { "atalanish", " Root word (verb) is made from noun" },
            { "atalanuv", " Root word (verb) is made from noun" },
            { "atalish", " Root word (verb) is made from noun" },
            { "atan", " root word - verb" },
            { "atangan", "Root word is verb" },
            { "atash", " Root word (verb) is made from noun" },
            { "atashtir", " Root word is verb" },
            { "atashtiril", "Root word is verb" },
            { "atashtirish", " Root word (verb) is made from noun" },
            { "atashtiruv", " Root word (verb) is made from noun" },
            { "atirla", " root word - verb" },
            { "atirsochdi", " root word - verb" },
            { "atlant", " root word - verb" },
            { "ato", " root word - verb" },
            { "atoqda", " root word - verb" },
            { "atoqla", " root word - verb" },
            { "atrofla", " root word - verb" },
            { "atroflat", " Root word is verb" },
            { "atroflatish", " Root word (verb) is made from noun" },
            { "atsetillash", " Root word (verb) is made from noun" },
            { "atsillash", " Root word (verb) is made from noun" },
            { "attangla", " root word - verb" },
            { "attanglov", " Root word (verb) is made from noun" },
            { "aut", " root word - verb" },
            { "avansla", " root word - verb" },
            { "avanslangan", "Root word is verb" },
            { "avarchalash", " Root word (verb) is made from noun" },
            { "avarchalashtir", " Root word is verb" },
            { "avavla", " root word - verb" },
            { "avayla", " root word - verb" },
            { "avaylash", " Root word (verb) is made from noun" },
            { "avaylov", " Root word (verb) is made from noun" },
            { "aviachanglash", " Root word (verb) is made from noun" },
            { "aviao'g'itlash", " Root word (verb) is made from noun" },
            { "avj ol", " root word - verb" },
            { "avjlan", " root word - verb" },
            { "avjlanish", " Root word (verb) is made from noun" },
            { "avjlantir", " Root word is verb" },
            { "avjlantirish", " Root word (verb) is made from noun" },
            { "avjlantiruv", " Root word (verb) is made from noun" },
            { "avjlanuv", " Root word (verb) is made from noun" },
            { "avomlash", " Root word (verb) is made from noun" },
            { "avomlashish", " Root word (verb) is made from noun" },
            { "avomlashuv", " Root word (verb) is made from noun" },
            { "avra", " root word - verb" },
            { "avral", " root word - verb" },
            { "avrala", " root word - verb" },
            { "avralat", " Root word is verb" },
            { "avralatish", " Root word (verb) is made from noun" },
            { "avralov", " Root word (verb) is made from noun" },
            { "avran", " root word - verb" },
            { "avrash", " Root word (verb) is made from noun" },
            { "avrashish", " Root word (verb) is made from noun" },
            { "avtoionlanish", " Root word (verb) is made from noun" },
            { "avtoionlash", " Root word (verb) is made from noun" },
            { "avtolokallanish", " Root word (verb) is made from noun" },
            { "avtolokallash", " Root word (verb) is made from noun" },
            { "avtomatlash", " root word - verb" },
            { "avtomatlashgan", "Root word is verb" },
            { "avtomatlashish", " Root word (verb) is made from noun" },
            { "avtomatlashtir", " root word - verb" },
            { "avtomatlashtiril", "Root word is verb" },
            { "avtomatlashtirish", " Root word (verb) is made from noun" },
            { "avtoregulyatsiyalash", " Root word (verb) is made from noun" },
            { "avtoriashtirilgan", "Root word is verb" },
            { "avtoriashtirish", " Root word (verb) is made from noun" },
            { "avtorlashtir", " Root word is verb" },
            { "avtotartiblash", " Root word (verb) is made from noun" },
            { "avtotebranish", " Root word (verb) is made from noun" },
            { "axtala", " root word - verb" },
            { "axtalantir", " Root word is verb" },
            { "axtalash", " Root word (verb) is made from noun" },
            { "axtalov", " Root word (verb) is made from noun" },
            { "axtar", " root word - verb" },
            { "axtarinish", " Root word (verb) is made from noun" },
            { "axtarish", " Root word (verb) is made from noun" },
            { "axtarishuv", " Root word (verb) is made from noun" },
            { "axtartir", " Root word is verb" },
            { "axtartirish", " Root word (verb) is made from noun" },
            { "axtartiruv", " Root word (verb) is made from noun" },
            { "axtaruv", " Root word (verb) is made from noun" },
            { "ay", " root word - verb" },
            { "aya", " root word - verb" },
            { "ayala", " root word - verb" },
            { "ayalash", " Root word (verb) is made from noun" },
            { "ayalashish", " Root word (verb) is made from noun" },
            { "ayaluv", " Root word (verb) is made from noun" },
            { "ayanish", " Root word (verb) is made from noun" },
            { "ayashish", " Root word (verb) is made from noun" },
            { "ayb qil", " root word - verb" },
            { "aybla", " root word - verb" },
            { "ayblan", " root word - verb" },
            { "ayblanish", " Root word (verb) is made from noun" },
            { "ayblantir", " Root word is verb" },
            { "ayblanuv", " Root word (verb) is made from noun" },
            { "ayblash", " Root word (verb) is made from noun" },
            { "aybsit", " root word - verb" },
            { "aybsitish", " Root word (verb) is made from noun" },
            { "aybsituv", " Root word (verb) is made from noun" },
            { "ayg'oqla", " root word - verb" },
            { "ayhaylash", " Root word (verb) is made from noun" },
            { "ayhaylashish", " Root word (verb) is made from noun" },
            { "ayhaylat", " Root word is verb" },
            { "ayhaylatish", " Root word (verb) is made from noun" },
            { "ayhaylov", " Root word (verb) is made from noun" },
            { "ayilish", " Root word (verb) is made from noun" },
            { "ayir", " root word - verb" },
            { "ayirboshla", " root word - verb" },
            { "ayirboshlan", " root word - verb" },
            { "ayirboshlash", " Root word (verb) is made from noun" },
            { "ayirboshlov", " Root word (verb) is made from noun" },
            { "ayirish", " Root word (verb) is made from noun" },
            { "ayirtir", " Root word is verb" },
            { "ayiruv", " Root word (verb) is made from noun" },
            { "ayla", " root word - verb" },
            { "aylamak", " Root word (verb) is made from noun" },
            { "aylan", " root word - verb" },
            { "aylanib-o'rgil", " root word - verb" },
            { "aylanish", " Root word (verb) is made from noun" },
            { "aylant", " root word - verb" },
            { "aylantir", " Root word is verb" },
            { "aylantirgiz", " Root word is verb" },
            { "aylantiril", "Root word is verb" },
            { "aylantirish", " Root word (verb) is made from noun" },
            { "aylantiruv", " Root word (verb) is made from noun" },
            { "aylanuv", " Root word (verb) is made from noun" },
            { "aymash", " root word - verb" },
            { "ayna", " root word - verb" },
            { "aynanlashtirish", " Root word (verb) is made from noun" },
            { "aynatish", " Root word (verb) is made from noun" },
            { "aynattir", " Root word is verb" },
            { "ayni", " root word - verb" },
            { "aynigan", "Root word is verb" },
            { "aynit", " Root word is verb" },
            { "aynitish", " Root word (verb) is made from noun" },
            { "ayonlash", " root word - verb" },
            { "ayovsira", " root word - verb" },
            { "ayozla", " root word - verb" },
            { "ayqash", " root word - verb" },
            { "ayqashish", " Root word (verb) is made from noun" },
            { "ayqashtir", " Root word is verb" },
            { "ayqashtirish", " Root word (verb) is made from noun" },
            { "ayqashtiruv", " Root word (verb) is made from noun" },
            { "ayqashuv", " Root word (verb) is made from noun" },
            { "ayqir", " root word - verb" },
            { "ayqirtir", " Root word is verb" },
            { "ayqirtirish", " Root word (verb) is made from noun" },
            { "ayqishla", " root word - verb" },
            { "ayqishlov", " Root word (verb) is made from noun" },
            { "ayri tush", " root word - verb" },
            { "ayriboshla", " root word - verb" },
            { "ayriboshlan", " root word - verb" },
            { "ayriboshlattir", " Root word is verb" },
            { "ayriboshlov", " Root word (verb) is made from noun" },
            { "ayril", " root word - verb" },
            { "ayrilgan", "Root word is verb" },
            { "ayrilish", " Root word (verb) is made from noun" },
            { "ayrilishuv", " Root word (verb) is made from noun" },
            { "ayriltir", " root word - verb" },
            { "ayriluv", " Root word (verb) is made from noun" },
            { "ayrimla", " root word - verb" },
            { "ayrimlan", "Root word is verb" },
            { "ayrimlanish", " Root word (verb) is made from noun" },
            { "ayrimlanuv", " Root word (verb) is made from noun" },
            { "ayrimlash", " Root word (verb) is made from noun" },
            { "ayt", " root word - verb" },
            { "ayta", " root word - verb" },
            { "aytadigan", "Root word is verb" },
            { "aytdi-qo'ydi", " root word - verb" },
            { "aytil", "Root word is verb" },
            { "aytilish", " Root word (verb) is made from noun" },
            { "aytiluv", " Root word (verb) is made from noun" },
            { "aytish", " root word - verb" },
            { "aytishtir", " root word - verb" },
            { "aytishtirish", " Root word (verb) is made from noun" },
            { "aytishtiruv", " Root word (verb) is made from noun" },
            { "aytmoq-qoy", " root word - verb" },
            { "aytol", " root word - verb" },
            { "ayttir", " Root word is verb" },
            { "ayttirgiz", " Root word is verb" },
            { "ayttiril", "Root word is verb" },
            { "ayttirish", " Root word (verb) is made from noun" },
            { "ayttiruv", " Root word (verb) is made from noun" },
            { "aytuv", " Root word (verb) is made from noun" },
            { "ayyorianish", " Root word (verb) is made from noun" },
            { "ayyorlan", " root word - verb" },
            { "aza tut", " root word - verb" },
            { "azizla", " root word - verb" },
            { "azizlan", "Root word is verb" },
            { "azizlanish", " Root word (verb) is made from noun" },
            { "azizlanuv", " Root word (verb) is made from noun" },
            { "azizlash", " Root word (verb) is made from noun" },
            { "azm qil", " root word - verb" },
            { "azob ber", " root word - verb" },
            { "azobirikish", " Root word (verb) is made from noun" },
            { "azobla", " root word - verb" },
            { "azoblan", " root word - verb" },
            { "azoblanish", " Root word (verb) is made from noun" },
            { "azoblantir", " Root word is verb" },
            { "azoblantirish", " Root word (verb) is made from noun" },
            { "azoblanuv", " Root word (verb) is made from noun" },
            { "azoblash", " Root word (verb) is made from noun" },
            { "azoblov", " Root word (verb) is made from noun" },
            { "azotla", " root word - verb" },
            { "azotlan", " root word - verb" },
            { "azotlanish", " Root word (verb) is made from noun" },
            { "azotlash", " Root word (verb) is made from noun" },
            { "azotlashtir", " Root word is verb" },
            { "azotlashtirish", " Root word (verb) is made from noun" },
            { "azotlov", " Root word (verb) is made from noun" },
            { "babala", " root word - verb" },
            { "babalash", " Root word (verb) is made from noun" },
            { "babalov", " Root word (verb) is made from noun" },
            { "bachkanalash", " root word - verb" },
            { "bachkanalashish", " Root word (verb) is made from noun" },
            { "bachkanalashitr", " root word - verb" },
            { "bachkanalashtir", " Root word is verb" },
            { "bachkila", " root word - verb" },
            { "bachkilash", " Root word (verb) is made from noun" },
            { "bachkilat", " Root word is verb" },
            { "badarg‘a bo‘l", " root word - verb" },
            { "badarg‘a qil", " root word - verb" },
            { "badavlatlash", " Root word (verb) is made from noun" },
            { "badbinlash", " Root word (verb) is made from noun" },
            { "badbo'ylan", " Root word (verb) is made from noun" },
            { "badbo'ylash", " Root word (verb) is made from noun" },
            { "badburushlan", " Root word (verb) is made from noun" },
            { "badfe'llash", " Root word (verb) is made from noun" },
            { "badhazmlash", " Root word (verb) is made from noun" },
            { "badhollan", " root word - verb" },
            { "badiriov", " Root word (verb) is made from noun" },
            { "badirla", " root word - verb" },
            { "badirlash", " Root word (verb) is made from noun" },
            { "badirlashish", " Root word (verb) is made from noun" },
            { "badlan", " root word - verb" },
            { "badnafslash", " Root word (verb) is made from noun" },
            { "badnafslashish", " Root word (verb) is made from noun" },
            { "badnafslashuv", " Root word (verb) is made from noun" },
            { "badnomlanish", " Root word (verb) is made from noun" },
            { "badnomlash", " Root word (verb) is made from noun" },
            { "badtarlash", " root word - verb" },
            { "badxo'rlash", " Root word (verb) is made from noun" },
            { "bag‘illa", " root word - verb" },
            { "bag‘irla", " root word - verb" },
            { "bag‘ishla", " root word - verb" },
            { "bag'illash", " Root word (verb) is made from noun" },
            { "bag'illashuv", " Root word (verb) is made from noun" },
            { "bag'illat", " Root word is verb" },
            { "bag'illatish", " Root word (verb) is made from noun" },
            { "bag'illov", " Root word (verb) is made from noun" },
            { "bag'irlab", " root word - verb" },
            { "bag'irlash", " Root word (verb) is made from noun" },
            { "bag'irlov", " Root word (verb) is made from noun" },
            { "bag'ish", " Root word (verb) is made from noun" },
            { "bag'ishlama", " root word - verb" },
            { "bag'ishlan", " root word - verb" },
            { "bag'ishlanil", "Root word is verb" },
            { "bag'ishlattir", " Root word is verb" },
            { "bag'ishlov", " Root word (verb) is made from noun" },
            { "baham", " root word - verb" },
            { "bahbahla", " root word - verb" },
            { "bahola", " root word - verb" },
            { "baholan", " root word - verb" },
            { "baholanish", " Root word (verb) is made from noun" },
            { "baholash", " root word - verb" },
            { "baholatish", " Root word (verb) is made from noun" },
            { "baholattir", " Root word is verb" },
            { "baholov", " Root word (verb) is made from noun" },
            { "bahralan", " root word - verb" },
            { "bahralanish", " Root word (verb) is made from noun" },
            { "bahralantir", " Root word is verb" },
            { "bahralanuv", " Root word (verb) is made from noun" },
            { "bahslash", " root word - verb" },
            { "bahslashish", " Root word (verb) is made from noun" },
            { "bahslashtir", " Root word is verb" },
            { "bahuzurlan", " root word - verb" },
            { "bajar", " root word - verb" },
            { "bajargiz", " root word - verb" },
            { "bajaril", "Root word is verb" },
            { "bajarilish", " Root word (verb) is made from noun" },
            { "bajarish", " Root word (verb) is made from noun" },
            { "bajarol", " root word - verb" },
            { "bajart", " Root word is verb" },
            { "bajartir", " Root word is verb" },
            { "bajartirish", " Root word (verb) is made from noun" },
            { "bajartiruv", " Root word (verb) is made from noun" },
            { "bajaruv", " Root word (verb) is made from noun" },
            { "bajo et", " root word - verb" },
            { "bajo qil", " root word - verb" },
            { "bakor", " root word - verb" },
            { "balandla", " root word - verb" },
            { "balandlash", " Root word (verb) is made from noun" },
            { "balandlashish", " Root word (verb) is made from noun" },
            { "balandlashuv", " Root word (verb) is made from noun" },
            { "balandlat", " root word - verb" },
            { "balandlatish", " Root word (verb) is made from noun" },
            { "balandlatuv", " Root word (verb) is made from noun" },
            { "balansla", " root word - verb" },
            { "balanslash", " Root word (verb) is made from noun" },
            { "balanslashtir", " Root word is verb" },
            { "balanslashtirish", " Root word (verb) is made from noun" },
            { "balanslov", " Root word (verb) is made from noun" },
            { "balchiqlan", " root word - verb" },
            { "balchiqlanish", " Root word (verb) is made from noun" },
            { "balish", " Root word (verb) is made from noun" },
            { "ballastlash", " Root word (verb) is made from noun" },
            { "balma", " root word - verb" },
            { "balqi", " root word - verb" },
            { "balqish", " Root word (verb) is made from noun" },
            { "balqit", " root word - verb" },
            { "balqitish", " Root word (verb) is made from noun" },
            { "balujchala", " root word - verb" },
            { "balzamla", " root word - verb" },
            { "balzamlash", " Root word (verb) is made from noun" },
            { "balzamlov", " Root word (verb) is made from noun" },
            { "band-bo'g'ov", " Root word (verb) is made from noun" },
            { "bandla", " root word - verb" },
            { "bandlan", " root word - verb" },
            { "bankrotlash", " root word - verb" },
            { "bankrotlashish", " Root word (verb) is made from noun" },
            { "banotunna'sh", " Root word (verb) is made from noun" },
            { "baqilla", " root word - verb" },
            { "baqir", " root word - verb" },
            { "baqira-baqira", " root word - verb" },
            { "baqirib-chaqirib", " root word - verb" },
            { "baqirish", " root word - verb" },
            { "baqirla", " root word - verb" },
            { "baqirtir", " root word - verb" },
            { "baqirtirish", " Root word (verb) is made from noun" },
            { "baqirtiruv", " Root word (verb) is made from noun" },
            { "baqiruv", " Root word (verb) is made from noun" },
            { "baqray", " root word - verb" },
            { "baqrayish", " Root word (verb) is made from noun" },
            { "baqrayt", " root word - verb" },
            { "baqraytir", " root word - verb" },
            { "baqraytirish", " Root word (verb) is made from noun" },
            { "baqrayuv", " Root word (verb) is made from noun" },
            { "baquvvatlan", " root word - verb" },
            { "barakatop", " root word - verb" },
            { "baralla", " root word - verb" },
            { "baravar kel", " root word - verb" },
            { "baravar ko‘r", " root word - verb" },
            { "baravarla", " root word - verb" },
            { "baravarlanish", " Root word (verb) is made from noun" },
            { "baravarlash", " root word - verb" },
            { "baravarlashish", " Root word (verb) is made from noun" },
            { "baravarlashtir", " Root word is verb" },
            { "baravarlashtirilgan", "Root word is verb" },
            { "baravarlashtirish", " Root word (verb) is made from noun" },
            { "baravarlashuv", " Root word (verb) is made from noun" },
            { "barbod bo‘l", " root word - verb" },
            { "barbod qil", " root word - verb" },
            { "barbodla", " root word - verb" },
            { "bardamlan", " root word - verb" },
            { "bardamlash", " root word - verb" },
            { "bardamlashish", " Root word (verb) is made from noun" },
            { "bardast", " root word - verb" },
            { "bardor-bardor qil", " root word - verb" },
            { "bardosh ber", " root word - verb" },
            { "bargla", " root word - verb" },
            { "barglat", " Root word is verb" },
            { "barglov", " Root word (verb) is made from noun" },
            { "bargsizlan", " root word - verb" },
            { "bargsizlanish", " Root word (verb) is made from noun" },
            { "bargsizlantirish", " Root word (verb) is made from noun" },
            { "baritlashish", " Root word (verb) is made from noun" },
            { "barkamollash", " Root word (verb) is made from noun" },
            { "barkarola", " root word - verb" },
            { "barkashkeldi", " root word - verb" },
            { "barkashla", " root word - verb" },
            { "barobarla", " root word - verb" },
            { "barobarlash", " Root word (verb) is made from noun" },
            { "barobarlashish", " Root word (verb) is made from noun" },
            { "barobarlashtir", " Root word is verb" },
            { "barobarlashtirilgan", "Root word is verb" },
            { "barobarlashtirish", " Root word (verb) is made from noun" },
            { "barobarlashuv", " Root word (verb) is made from noun" },
            { "barq ur", " root word - verb" },
            { "barqarorlan", " root word - verb" },
            { "barqarorlanish", " Root word (verb) is made from noun" },
            { "barqarorlash", " Root word (verb) is made from noun" },
            { "barqarorlashuv", " Root word (verb) is made from noun" },
            { "barqira", " root word - verb" },
            { "bartaraf qil", " root word - verb" },
            { "bartarafla", " root word - verb" },
            { "bartaraflan", " root word - verb" },
            { "bartaraflanish", " Root word (verb) is made from noun" },
            { "bas qil", " root word - verb" },
            { "bashangla", " root word - verb" },
            { "bashanglash", " Root word (verb) is made from noun" },
            { "basitlan", " root word - verb" },
            { "basitlantir", " Root word is verb" },
            { "basitlash", " Root word (verb) is made from noun" },
            { "baski", " root word - verb" },
            { "basla", " root word - verb" },
            { "baslan", " root word - verb" },
            { "baslanish", " Root word (verb) is made from noun" },
            { "baslash", " root word - verb" },
            { "baslashish", " Root word (verb) is made from noun" },
            { "baslashuv", " Root word (verb) is made from noun" },
            { "basma", " root word - verb" },
            { "basmabaslash", " root word - verb" },
            { "basmabaslashish", " Root word (verb) is made from noun" },
            { "bastala", " root word - verb" },
            { "bastalan", " root word - verb" },
            { "bastalanish", " Root word (verb) is made from noun" },
            { "bastalash", " Root word (verb) is made from noun" },
            { "bastalov", " Root word (verb) is made from noun" },
            { "batar", " root word - verb" },
            { "batash", " Root word (verb) is made from noun" },
            { "batraklash", " root word - verb" },
            { "batraklashish", " Root word (verb) is made from noun" },
            { "battarlash", " root word - verb" },
            { "baxillan", " root word - verb" },
            { "baxillash", " Root word (verb) is made from noun" },
            { "baxillashish", " Root word (verb) is made from noun" },
            { "baxillashuv", " Root word (verb) is made from noun" },
            { "baxsh et", " root word - verb" },
            { "baxyala", " root word - verb" },
            { "baxyalat", " root word - verb" },
            { "baxyalov", " Root word (verb) is made from noun" },
            { "baybayla", " root word - verb" },
            { "baybaylash", " Root word (verb) is made from noun" },
            { "baybaylashuv", " Root word (verb) is made from noun" },
            { "baybaylat", " Root word is verb" },
            { "baybaylov", " Root word (verb) is made from noun" },
            { "bayirlash", " root word - verb" },
            { "baylash", " root word - verb" },
            { "bayonla", " root word - verb" },
            { "bayonlov", " Root word (verb) is made from noun" },
            { "bayovlash", " Root word (verb) is made from noun" },
            { "bayramlash", " root word - verb" },
            { "bayrilash", " Root word (verb) is made from noun" },
            { "beburdlan", " root word - verb" },
            { "beburdlanish", " Root word (verb) is made from noun" },
            { "beburdlantir", " Root word is verb" },
            { "bedorlan", " root word - verb" },
            { "bedorlanish", " Root word (verb) is made from noun" },
            { "bedorlantir", " Root word is verb" },
            { "befarosatlan", " root word - verb" },
            { "befarosatlash", " root word - verb" },
            { "befarq qara", " root word - verb" },
            { "beg'amlan", "Root word is verb" },
            { "beg'amlanish", " Root word (verb) is made from noun" },
            { "beg'amlanuv", " Root word (verb) is made from noun" },
            { "begish", " Root word (verb) is made from noun" },
            { "beglamish", " Root word (verb) is made from noun" },
            { "begonalash", " root word - verb" },
            { "begonalashish", " Root word (verb) is made from noun" },
            { "begonalashtir", " Root word is verb" },
            { "begonalashtiril", "Root word is verb" },
            { "begonalashuv", " Root word (verb) is made from noun" },
            { "begonasira", " root word - verb" },
            { "begonasirash", " Root word (verb) is made from noun" },
            { "behbehla", " root word - verb" },
            { "behollanish", " Root word (verb) is made from noun" },
            { "behush qil", " root word - verb" },
            { "behushlan", " root word - verb" },
            { "behushlantir", " Root word is verb" },
            { "behushlantiradigan", "Root word is verb" },
            { "behushlantiril", "Root word is verb" },
            { "behushlanuv", " Root word (verb) is made from noun" },
            { "behuzur bo‘l", " root word - verb" },
            { "behuzurlan", " root word - verb" },
            { "beja", " root word - verb" },
            { "bejash", " Root word (verb) is made from noun" },
            { "bejolan", " root word - verb" },
            { "bekil", " root word - verb" },
            { "bekilish", " Root word (verb) is made from noun" },
            { "bekin", " root word - verb" },
            { "bekinish", " Root word (verb) is made from noun" },
            { "bekit", " root word - verb" },
            { "bekitil", "Root word is verb" },
            { "bekitish", " Root word (verb) is made from noun" },
            { "bekittir", " Root word is verb" },
            { "bekittiril", "Root word is verb" },
            { "bekittiruv", " Root word (verb) is made from noun" },
            { "bekituv", " Root word (verb) is made from noun" },
            { "bekkelit", " Root word is verb" },
            { "bekla", " root word - verb" },
            { "beklan", " root word - verb" },
            { "beklash", " Root word (verb) is made from noun" },
            { "beklov", " Root word (verb) is made from noun" },
            { "bela", " root word - verb" },
            { "belab", " root word - verb" },
            { "belan", " root word - verb" },
            { "belanish", " Root word (verb) is made from noun" },
            { "belantir", " Root word is verb" },
            { "belantirish", " Root word (verb) is made from noun" },
            { "belash", " root word - verb" },
            { "belayit", " Root word is verb" },
            { "belbo'g'ar", " root word - verb" },
            { "belchala", " root word - verb" },
            { "belgila", " root word - verb" },
            { "belgilan", " root word - verb" },
            { "belgilanish", " Root word (verb) is made from noun" },
            { "belgilat", " Root word is verb" },
            { "belgilatish", " Root word (verb) is made from noun" },
            { "belgilov", " Root word (verb) is made from noun" },
            { "belilla", " root word - verb" },
            { "belillanish", " Root word (verb) is made from noun" },
            { "belillov", " Root word (verb) is made from noun" },
            { "bella", " root word - verb" },
            { "bellash", " root word - verb" },
            { "bellashish", " Root word (verb) is made from noun" },
            { "bellashtir", " Root word is verb" },
            { "bellashtirish", " Root word (verb) is made from noun" },
            { "bellat", " Root word is verb" },
            { "bellatish", " Root word (verb) is made from noun" },
            { "bellit", " Root word is verb" },
            { "belma-bel olish", " root word - verb" },
            { "beloruschala", " root word - verb" },
            { "belovit", " Root word is verb" },
            { "bemadorlan", " root word - verb" },
            { "bemaza qil", " root word - verb" },
            { "bemazalash", " root word - verb" },
            { "bemazalashtir", " Root word is verb" },
            { "bemorlan", " root word - verb" },
            { "bemorlanish", " Root word (verb) is made from noun" },
            { "bengza", " root word - verb" },
            { "beobro‘ qil", " root word - verb" },
            { "beobro'lan", " root word - verb" },
            { "beo'lchov", " Root word (verb) is made from noun" },
            { "beorlan", " root word - verb" },
            { "beorlanish", " Root word (verb) is made from noun" },
            { "beorlash", " Root word (verb) is made from noun" },
            { "beorlashish", " Root word (verb) is made from noun" },
            { "beparvolash", " Root word (verb) is made from noun" },
            { "beparvolashish", " Root word (verb) is made from noun" },
            { "bepushtlashtirish", " Root word (verb) is made from noun" },
            { "beqarov", " Root word (verb) is made from noun" },
            { "ber", " root word - verb" },
            { "bera", " root word - verb" },
            { "berahmlash", " Root word (verb) is made from noun" },
            { "beraver", " root word - verb" },
            { "berayotir", " root word - verb" },
            { "berber", " root word - verb" },
            { "berberin", " root word - verb" },
            { "berdir", " Root word is verb" },
            { "berdirish", " Root word (verb) is made from noun" },
            { "berdirtir", " Root word is verb" },
            { "berdirtiruv", " Root word (verb) is made from noun" },
            { "berdiruv", " Root word (verb) is made from noun" },
            { "berezit", " Root word is verb" },
            { "berezovit", " Root word is verb" },
            { "bergan", "Root word is verb" },
            { "bergan-bermagan", "Root word is verb" },
            { "bergizdir", " Root word is verb" },
            { "bergizdirish", " Root word (verb) is made from noun" },
            { "bergizish", " Root word (verb) is made from noun" },
            { "bergizuv", " Root word (verb) is made from noun" },
            { "beril", " root word - verb" },
            { "berilish", " Root word (verb) is made from noun" },
            { "berilliylash", " Root word (verb) is made from noun" },
            { "beriluv", " Root word (verb) is made from noun" },
            { "berish", " root word - verb" },
            { "berish-tutish", " Root word (verb) is made from noun" },
            { "berkil", " root word - verb" },
            { "berkilish", " Root word (verb) is made from noun" },
            { "berkin", " root word - verb" },
            { "berkinish", " Root word (verb) is made from noun" },
            { "berkit", " Root word is verb" },
            { "berkitil", "Root word is verb" },
            { "berkitish", " Root word (verb) is made from noun" },
            { "berkittir", " Root word is verb" },
            { "berkittiril", "Root word is verb" },
            { "berkittiruv", " Root word (verb) is made from noun" },
            { "berkituv", " Root word (verb) is made from noun" },
            { "berkla", " root word - verb" },
            { "berklan", " root word - verb" },
            { "berklash", " Root word (verb) is made from noun" },
            { "berklov", " Root word (verb) is made from noun" },
            { "berkshir", " Root word is verb" },
            { "berlinit", " Root word is verb" },
            { "berma", " root word - verb" },
            { "bermas", " root word - verb" },
            { "bermasdan", " root word - verb" },
            { "bermas-qo'ymas", " root word - verb" },
            { "bermoqchi", " root word - verb" },
            { "berol", " root word - verb" },
            { "bersh", " Root word (verb) is made from noun" },
            { "bersim", " root word - verb" },
            { "bers-not", " root word - verb" },
            { "beruv", " Root word (verb) is made from noun" },
            { "besabrlan", " root word - verb" },
            { "besaiianish", " Root word (verb) is made from noun" },
            { "besarlan", " root word - verb" },
            { "beshovlash", " Root word (verb) is made from noun" },
            { "beshovlashish", " Root word (verb) is made from noun" },
            { "beso'naqaylash", " Root word (verb) is made from noun" },
            { "beso'naqaylashuv", " Root word (verb) is made from noun" },
            { "bessemerlash", " Root word (verb) is made from noun" },
            { "beta-aylanish", " Root word (verb) is made from noun" },
            { "betamizlash", " Root word (verb) is made from noun" },
            { "betamizlashish", " Root word (verb) is made from noun" },
            { "betamizlashuv", " Root word (verb) is made from noun" },
            { "beta-nurlanish", " Root word (verb) is made from noun" },
            { "beta-o'lchash", " Root word (verb) is made from noun" },
            { "beta-o'tish", " Root word (verb) is made from noun" },
            { "beta-o'zgarish", " Root word (verb) is made from noun" },
            { "beta-parchalanish", " Root word (verb) is made from noun" },
            { "betaraflash", " Root word (verb) is made from noun" },
            { "betaraflashtiril", "Root word is verb" },
            { "betartiblan", " root word - verb" },
            { "betartiblash", " root word - verb" },
            { "betashvishlan", " root word - verb" },
            { "beta'sirlan", " root word - verb" },
            { "beta-yemirilish", " Root word (verb) is made from noun" },
            { "betinchlan", " root word - verb" },
            { "betinchlanish", " Root word (verb) is made from noun" },
            { "betinchlash", " Root word (verb) is made from noun" },
            { "betla", " root word - verb" },
            { "betlama", " root word - verb" },
            { "betlan", " root word - verb" },
            { "betlash", " Root word (verb) is made from noun" },
            { "betlashtir", " root word - verb" },
            { "betlashtirish", " Root word (verb) is made from noun" },
            { "betlat", " Root word is verb" },
            { "betoblan", " root word - verb" },
            { "betoblanish", " Root word (verb) is made from noun" },
            { "betoblanuv", " Root word (verb) is made from noun" },
            { "betonla", " root word - verb" },
            { "betonlan", " root word - verb" },
            { "betonlash", " Root word (verb) is made from noun" },
            { "betonlov", " Root word (verb) is made from noun" },
            { "betoqatlan", " root word - verb" },
            { "betoqatlanish", " Root word (verb) is made from noun" },
            { "beuquv", " Root word (verb) is made from noun" },
            { "bevalash", " Root word (verb) is made from noun" },
            { "bevoshlan", "Root word is verb" },
            { "beyuzlash", " Root word (verb) is made from noun" },
            { "beyza", " root word - verb" },
            { "bez bo‘l", " root word - verb" },
            { "beza", " root word - verb" },
            { "bezab-bo'yab", " root word - verb" },
            { "bezakla", " root word - verb" },
            { "bezaklan", " root word - verb" },
            { "bezal", " root word - verb" },
            { "bezalish", " Root word (verb) is made from noun" },
            { "bezaltir", " Root word (verb) is made from noun" },
            { "bezama", " root word - verb" },
            { "bezan", " root word - verb" },
            { "bezangla", " root word - verb" },
            { "bezanglat", " Root word is verb" },
            { "bezanglatish", " Root word (verb) is made from noun" },
            { "bezanil", "Root word is verb" },
            { "bezanish", " Root word (verb) is made from noun" },
            { "bezanma", " root word - verb" },
            { "bezantir", " Root word is verb" },
            { "bezantirish", " Root word (verb) is made from noun" },
            { "bezantiruv", " Root word (verb) is made from noun" },
            { "bezanuv", " Root word (verb) is made from noun" },
            { "bezarish", " Root word (verb) is made from noun" },
            { "bezartir", " Root word is verb" },
            { "bezartirish", " Root word (verb) is made from noun" },
            { "bezartiruv", " Root word (verb) is made from noun" },
            { "bezaruv", " Root word (verb) is made from noun" },
            { "bezash", " Root word (verb) is made from noun" },
            { "bezashish", " Root word (verb) is made from noun" },
            { "bezashuv", " Root word (verb) is made from noun" },
            { "bezat", " Root word is verb" },
            { "bezatil", "Root word is verb" },
            { "bezatilish", " Root word (verb) is made from noun" },
            { "bezatish", " Root word (verb) is made from noun" },
            { "bezatma", " root word - verb" },
            { "bezattir", " Root word is verb" },
            { "bezattiril", "Root word is verb" },
            { "bezattirish", " Root word (verb) is made from noun" },
            { "bezattiruv", " Root word (verb) is made from noun" },
            { "bezatuv", " Root word (verb) is made from noun" },
            { "bezbetlash", " Root word (verb) is made from noun" },
            { "bezbetlashish", " Root word (verb) is made from noun" },
            { "bez-bez qil", " root word - verb" },
            { "bezbezla", " root word - verb" },
            { "bezdir", " root word - verb" },
            { "bezdiril", "Root word is verb" },
            { "bezdirish", " Root word (verb) is made from noun" },
            { "bezdirtir", " Root word is verb" },
            { "bezdirtirish", " Root word (verb) is made from noun" },
            { "bezdiruv", " Root word (verb) is made from noun" },
            { "beze", " root word - verb" },
            { "bezilla", " root word - verb" },
            { "bezillash", " Root word (verb) is made from noun" },
            { "bezillat", " Root word is verb" },
            { "bezillatish", " Root word (verb) is made from noun" },
            { "bezillov", " Root word (verb) is made from noun" },
            { "bezit", " Root word is verb" },
            { "bezitish", " Root word (verb) is made from noun" },
            { "bezlashish", " Root word (verb) is made from noun" },
            { "bezor bo‘l", " root word - verb" },
            { "bezorilash", " Root word (verb) is made from noun" },
            { "bezorilashish", " Root word (verb) is made from noun" },
            { "bezovtala", " root word - verb" },
            { "bezovtalan", " root word - verb" },
            { "bezovtalanish", " Root word (verb) is made from noun" },
            { "bezovtalantir", " Root word is verb" },
            { "bezray", " root word - verb" },
            { "bezrayish", " Root word (verb) is made from noun" },
            { "bezraytir", " Root word is verb" },
            { "bezraytirish", " Root word (verb) is made from noun" },
            { "bezraytiruv", " Root word (verb) is made from noun" },
            { "bezrayuv", " Root word (verb) is made from noun" },
            { "bibliografiyalash", " root word - verb" },
            { "bich", " root word - verb" },
            { "bichib-to‘qi", " root word - verb" },
            { "bichil", " root word - verb" },
            { "bichilgan", "Root word is verb" },
            { "bichilmagan", "Root word is verb" },
            { "bichiltir", " Root word is verb" },
            { "bichir", " Root word is verb" },
            { "bichirish", " Root word (verb) is made from noun" },
            { "bichirtir", " Root word is verb" },
            { "bichirtirish", " Root word (verb) is made from noun" },
            { "bichiruv", " Root word (verb) is made from noun" },
            { "bichish", " Root word (verb) is made from noun" },
            { "bichma", " root word - verb" },
            { "bichtir", " Root word is verb" },
            { "bichtiril", "Root word is verb" },
            { "bichtirish", " Root word (verb) is made from noun" },
            { "bichuv", " Root word (verb) is made from noun" },
            { "bidilla", " root word - verb" },
            { "bidirla", " root word - verb" },
            { "bidirlash", " Root word (verb) is made from noun" },
            { "bidirlov", " Root word (verb) is made from noun" },
            { "bidistillanish", " Root word (verb) is made from noun" },
            { "big‘illa", " root word - verb" },
            { "big'big'la", " root word - verb" },
            { "big'illash", " Root word (verb) is made from noun" },
            { "big'illat", " Root word is verb" },
            { "big'illatish", " Root word (verb) is made from noun" },
            { "big'irla", " root word - verb" },
            { "big'irlash", " Root word (verb) is made from noun" },
            { "big'irlov", " Root word (verb) is made from noun" },
            { "bigizla", " root word - verb" },
            { "bigizlov", " Root word (verb) is made from noun" },
            { "bijbijla", " root word - verb" },
            { "bijg‘i", " root word - verb" },
            { "bijg'ish", " Root word (verb) is made from noun" },
            { "bijg'it", " Root word is verb" },
            { "bijg'itish", " Root word (verb) is made from noun" },
            { "bijg'uv", " Root word (verb) is made from noun" },
            { "biji", " root word - verb" },
            { "bijilla", " root word - verb" },
            { "bijillash", " Root word (verb) is made from noun" },
            { "bijirla", " root word - verb" },
            { "bijirlash", " Root word (verb) is made from noun" },
            { "bijirlov", " Root word (verb) is made from noun" },
            { "bil", " root word - verb" },
            { "bilaklash", " Root word (verb) is made from noun" },
            { "bilangla", " root word - verb" },
            { "bilanglash", " Root word (verb) is made from noun" },
            { "bilanglat", " Root word is verb" },
            { "bilarmonlik qil", " root word - verb" },
            { "bilaver", " root word - verb" },
            { "bilchilla", " root word - verb" },
            { "bilchillash", " Root word (verb) is made from noun" },
            { "bilchillat", " root word - verb" },
            { "bilchillov", " Root word (verb) is made from noun" },
            { "bilchira", " root word - verb" },
            { "bildir", " root word - verb" },
            { "bildirgiz", " root word - verb" },
            { "bildiril", "Root word is verb" },
            { "bildirtir", " Root word is verb" },
            { "bildirtirish", " Root word (verb) is made from noun" },
            { "bildirtiruv", " Root word (verb) is made from noun" },
            { "bildiruv", " Root word (verb) is made from noun" },
            { "bilgan", "Root word is verb" },
            { "bilgan-bilmagan", "Root word is verb" },
            { "bilgan-eshitgan", "Root word is verb" },
            { "bilgan-netgan", "Root word is verb" },
            { "bilgirlash", " Root word (verb) is made from noun" },
            { "bilgiz", " root word - verb" },
            { "bilgizish", " Root word (verb) is made from noun" },
            { "bilgizuv", " Root word (verb) is made from noun" },
            { "bilgut", " Root word is verb" },
            { "bilin", " root word - verb" },
            { "bilinish", " Root word (verb) is made from noun" },
            { "bilintir", " root word - verb" },
            { "bilintiril", "Root word is verb" },
            { "bilintirish", " Root word (verb) is made from noun" },
            { "bilinuv", " Root word (verb) is made from noun" },
            { "biliqsi", " root word - verb" },
            { "biliqsit", " Root word is verb" },
            { "biliqtir", " Root word is verb" },
            { "biliqtiruv", " Root word (verb) is made from noun" },
            { "bilish-qo'yish", " Root word (verb) is made from noun" },
            { "bilish-tanish", " Root word (verb) is made from noun" },
            { "biljing-biljing", " root word - verb" },
            { "biljira", " root word - verb" },
            { "biljirat", " Root word is verb" },
            { "biljiratish", " Root word (verb) is made from noun" },
            { "biljir-biljir", " root word - verb" },
            { "biljirov", " Root word (verb) is made from noun" },
            { "billurlan", " root word - verb" },
            { "billurlanish", " Root word (verb) is made from noun" },
            { "bilmak", " Root word (verb) is made from noun" },
            { "bilmam", " root word - verb" },
            { "bilmoqchi", " root word - verb" },
            { "bilqi", " root word - verb" },
            { "bilqilla", " root word - verb" },
            { "bilqillash", " Root word (verb) is made from noun" },
            { "bilqillat", " Root word is verb" },
            { "bilqillatish", " Root word (verb) is made from noun" },
            { "biltangla", " root word - verb" },
            { "biluv", " Root word (verb) is made from noun" },
            { "bintla", " root word - verb" },
            { "bintlash", " Root word (verb) is made from noun" },
            { "bintlov", " Root word (verb) is made from noun" },
            { "biotit", " Root word is verb" },
            { "bioyemirilish", " Root word (verb) is made from noun" },
            { "biq", " root word - verb" },
            { "biqilla", " root word - verb" },
            { "biqin", " root word - verb" },
            { "biqinla", " root word - verb" },
            { "biqintir", " Root word is verb" },
            { "biqirla", " root word - verb" },
            { "biqirlat", " Root word is verb" },
            { "biqsi", " root word - verb" },
            { "biqsima", " root word - verb" },
            { "biqsit", " Root word is verb" },
            { "biqtir", " Root word is verb" },
            { "biqtiril", "Root word is verb" },
            { "biqtirma", " root word - verb" },
            { "birgalash", " root word - verb" },
            { "birgalashish", " Root word is verb" },
            { "birgalashtir", " Root word is verb" },
            { "birik", " root word - verb" },
            { "biriktir", " Root word is verb" },
            { "biriktiril", "Root word is verb" },
            { "biriktirish", " Root word (verb) is made from noun" },
            { "biriktiruv", " Root word (verb) is made from noun" },
            { "birikuv", " Root word (verb) is made from noun" },
            { "birkit", " Root word is verb" },
            { "birkitil", " root word - verb" },
            { "birlan", " root word - verb" },
            { "birlash", " Root word (verb) is made from noun" },
            { "birlashgan", "Root word is verb" },
            { "birlashish", " Root word (verb) is made from noun" },
            { "birlashtir", " root word - verb" },
            { "birlashtiril", "Root word is verb" },
            { "birlashtirilgan", "Root word is verb" },
            { "birlashtirish", " Root word (verb) is made from noun" },
            { "birlashtiruv", " Root word (verb) is made from noun" },
            { "birlashuv", " Root word (verb) is made from noun" },
            { "birodarlash", " Root word (verb) is made from noun" },
            { "birodarlashgan", "Root word is verb" },
            { "birsidra", " root word - verb" },
            { "birxillash", " Root word (verb) is made from noun" },
            { "birxillashtirish", " Root word (verb) is made from noun" },
            { "bissektlash", " Root word (verb) is made from noun" },
            { "bissektrisa", " root word - verb" },
            { "bit", " root word - verb" },
            { "biter", " root word - verb" },
            { "bitgan-bitmagan", "Root word is verb" },
            { "bitil", " root word - verb" },
            { "bitir", " root word - verb" },
            { "bitiril", "Root woord is verb" },
            { "bitirilish", " Root word (verb) is made from noun" },
            { "bitirish", " Root word (verb) is made from noun" },
            { "bitirtir", " Root word is verb" },
            { "bitiruv", " Root word (verb) is made from noun" },
            { "bitish", " Root word (verb) is made from noun" },
            { "bitishish", " Root word (verb) is made from noun" },
            { "bitishma", " root word - verb" },
            { "bitishtir", " Root word is verb" },
            { "bitishtiril", "Root word is verb" },
            { "bitishtiruv", " Root word (verb) is made from noun" },
            { "bitishuv", " Root word (verb) is made from noun" },
            { "bitkaril", "Root word is verb" },
            { "bitkaz", " Root word is verb" },
            { "bitkiz", " Root word is verb" },
            { "bitla", " root word - verb" },
            { "bitlat", " Root word is verb" },
            { "bitlov", " Root word (verb) is made from noun" },
            { "bitumlanish", " Root word (verb) is made from noun" },
            { "biyla", " root word - verb" },
            { "biylat", " root word - verb" },
            { "biyronlash", " root word - verb" },
            { "bizilla", " root word - verb" },
            { "blanshirlash", " Root word (verb) is made from noun" },
            { "blokirlov", " Root word (verb) is made from noun" },
            { "bobilla", " root word - verb" },
            { "bobirla", " root word - verb" },
            { "bobla", " root word - verb" },
            { "boblan", " root word - verb" },
            { "boblash", " Root word (verb) is made from noun" },
            { "boblashtir", " Root word is verb" },
            { "bodenit", " Root word is verb" },
            { "bodilan", " root word - verb" },
            { "bodirla", " root word - verb" },
            { "bodra", " root word - verb" },
            { "bodrash", " Root word (verb) is made from noun" },
            { "bodrat", " Root word is verb" },
            { "bodratish", " Root word (verb) is made from noun" },
            { "bog‘ qil", " root word - verb" },
            { "bog‘la", " root word - verb" },
            { "bog‘lan", " root word - verb" },
            { "bog‘lanish", " Root word (verb) is made from noun" },
            { "bog‘lash", " Root word (verb) is made from noun" },
            { "bog‘lov", " Root word (verb) is made from noun" },
            { "bog'ichla", " root word - verb" },
            { "bog'ichlov", " Root word (verb) is made from noun" },
            { "bog'langan", "Root word is verb" },
            { "bog'lantir", " Root word is verb" },
            { "bog'lanuv", " Root word is verb" },
            { "bog'lashuv", " Root word (verb) is made from noun" },
            { "bog'lat", " Root word is verb" },
            { "bog'latish", " Root word (verb) is made from noun" },
            { "bog'latma", " root word - verb" },
            { "bog'lattir", " Root word is verb" },
            { "bog'lattirish", " Root word (verb) is made from noun" },
            { "bog'latuv", " Root word (verb) is made from noun" },
            { "bog'lovchilashish", " Root word (verb) is made from noun" },
            { "bojray", " root word - verb" },
            { "bovar ayla", " root word - verb" },
            { "bovar et", " root word - verb" },
            { "bovar qil", " root word - verb" },
            { "bozigar", "Root word is verb" },
            { "bozilla", " root word - verb" },
            { "bozillat", " Root word is verb" },
            { "bozillov", " Root word (verb) is made from noun" },
            { "bozor qil", " root word - verb" },
            { "bozorla", " root word - verb" },
            { "bozorlash", " Root word (verb) is made from noun" },
            { "bozorlashish", " Root word (verb) is made from noun" },
            { "bozorlashuv", " Root word (verb) is made from noun" },

            {"ishla", " Root word (verb) is made from noun" },
            {"ishlash", " Root word (verb) is made from noun" },
            {"so'zla", " Root word (verb) is made from noun" },
            {"so'zlash", " Root word (verb) is made from noun" }
        };
    }
}
